<a href="https://colab.research.google.com/github/AleenaMol-M/numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np #numpy-numerical python ,used to use advanced mathematical expressions

#array-collection of data with same datatype(homogenious)
a=np.array([1,2,3,4])
a=np.array([1,2,3.0,4])#converted all elements to float
a=np.array([1,2,3,4,"a"])#converted all elements to string
print(a)

['1' '2' '3' '4' 'a']


In [ ]:
#slicing-forward slicing and backward slicing

b=np.array([1,2,3,4,5])
print(b)
#print 1,2
print(b[0:2])

#print 5,4
print(b[-1:-3:-1])

#print 4,5
print(b[3:])

#print 2,1
print(b[-4::-1])

[1 2 3 4 5]
[1 2]
[5 4]
[4 5]
[2 1]


In [ ]:
#diamension
a=np.array([0,1,5])
a.ndim #ndim-to check dimension of an array
#diamension=1 vector

b=np.array([[1,2],[3,4]])
b.ndim#diamension=2 -matrix
print(b)
print(b.shape)#to know shape of aray(rows and columns)


c=np.array([[[1,2,3],[3,4,5]],[[3,4,8],[7,2,3]]])
c.ndim#diamension=3 -tensor


#3dimensional array-tensor

[[1 2]
 [3 4]]
(2, 2)


3

In [ ]:
#create a 2x2 matrix 2,3,4,5
a=np.array([[2,3],[4,5]])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)#to find total no of elements in a matrix

[[2 3]
 [4 5]]
2
(2, 2)
4


In [ ]:
#create a 2x3 matrix and print  the matrix,size,shape and dimension
a=np.array([[2,3,4],[3,4,5]])
print(a)
print(a.size)
print(a.shape)
print(a.ndim)

[[2 3 4]
 [3 4 5]]
6
(2, 3)
2


In [ ]:
#create a 4x2 matrix display its size ,shape ,dimension

b=np.array([[1,2],[4,5],[3,4],[5,6]])
print(b)
print(b.size)
print(b.shape)
print(b.ndim)

[[1 2]
 [4 5]
 [3 4]
 [5 6]]
8
(4, 2)
2


In [ ]:
#create a 4x4 matrix
import numpy as np
c=np.array([[2,3,4,5],[1,2,3,4],[2,2,5,6],[5,6,7,8]])
print(c)
print(c.ndim)
print(c.shape)
print(c.size)

[[2 3 4 5]
 [1 2 3 4]
 [2 2 5 6]
 [5 6 7 8]]
2
(4, 4)
16


In [ ]:

c[0]   #get 0th index of array c
c[:,0] #get 0th column c[row:row,column]/c[row,column]
c[0:2,0]#get 0 to 1st rows of 0th column

c[1,1] #to get 2 from second row
c[2,2]
c[3,2:]#to get [7,8] from 3rd row of 2nd and 3rd column
c[2:,2:]
c[1,2]
c[2:,1:3]
c[1:3,3]
c[1:3,0:3]
c[0:3,1:]
c[1:,]
c[:,1]
c[:,:]

array([[2, 3, 4, 5],
       [1, 2, 3, 4],
       [2, 2, 5, 6],
       [5, 6, 7, 8]])

In [ ]:
#zero matrix -all elements are zeros

z=np.zeros([3,3])#3X3 matrix
z=np.zeros([3,3,3],dtype=int)#dtype -convert datatype,3 3x3 matrix
z=np.zeros([3,3,3],dtype=complex)#a+ib
print(z)

[[[0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j]]

 [[0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j]]

 [[0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j]]]


In [ ]:
z=np.zeros([2,3,3])#two 3x3 matrix
print(z)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
#one matrix-all elements are 1
z=np.ones([3,3],dtype=int)
z

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
#create two 2x2 matrix
a=np.array([[1,2],[3,4]])
b=np.array([[3,8],[9,8]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[3 8]
 [9 8]]


In [ ]:
#matrix operations


#matrix addition
print(a+b)

#matrix subtraction
print(a-b)

#matrix multiplication

#a*b is not matrix multiplication
print(a@b)#matrix multiplication
print(a.dot(b))#matrix multiplication

#matrix division
print(a/b)      #magic __add__()-mathod strting with __ are called magic

[[ 4 10]
 [12 12]]
[[-2 -6]
 [-6 -4]]
[[21 24]
 [45 56]]
[[21 24]
 [45 56]]
[[0.33333333 0.25      ]
 [0.33333333 0.5       ]]


In [ ]:
#full matrix-all elements are same

z=np.full([3,3],4,dtype=int)#4 is the element
z

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
#create a 3x4 matrix with value 9 and datatype complex

a=np.full([3,4],9,dtype=complex)
print(a)

[[9.+0.j 9.+0.j 9.+0.j 9.+0.j]
 [9.+0.j 9.+0.j 9.+0.j 9.+0.j]
 [9.+0.j 9.+0.j 9.+0.j 9.+0.j]]


In [ ]:
#identity matrix-diagonal=1 and square matrix2
import numpy as np
z=np.identity(3,dtype=int)
print(z)
z=np.eye(3,dtype=int)
print(z)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
#create a 4x4 matrix
z=np.array([[1,2,3,4],[2,3,4,5],[4,5,6,7],[7,4,2,2]])
print(z)
print(z.size)
print(z.shape)

[[1 2 3 4]
 [2 3 4 5]
 [4 5 6 7]
 [7 4 2 2]]
16
(4, 4)


In [ ]:
a=z.reshape(16,1)#shape=16   (8,2)(16,1)(4,4)  #reshape to change shape
print(a)

[[1]
 [2]
 [3]
 [4]
 [2]
 [3]
 [4]
 [5]
 [4]
 [5]
 [6]
 [7]
 [7]
 [4]
 [2]
 [2]]


In [ ]:
#arange-to create array of particular range of numbers
a=np.arange(1,10,2)#(start,stop,step)
a

array([1, 3, 5, 7, 9])

In [ ]:
#create a 5x2 matrix using arange
a=np.arange(1,11).reshape(5,2)
print(a)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [ ]:
#create a 3x3 matrix with float values
a=np.array([[1.5,2.3,3.0],[1.2,4.5,3.5],[2.7,6.5,2.4]])
print(a)

[[1.5 2.3 3. ]
 [1.2 4.5 3.5]
 [2.7 6.5 2.4]]


In [ ]:
#floor-round to lowest integer
z=np.floor(a)
print(z)


[[1. 2. 3.]
 [1. 3. 1.]
 [2. 6. 2.]]


In [ ]:
#ceil-round to heighest integer
z=np.ceil(a)
print(z)

[[2. 3. 3.]
 [2. 4. 2.]
 [3. 7. 3.]]


In [ ]:
#round-to round numbers (.5 round towards even numbers)(4.5 ->4,3.5->4)
z=np.round(a)
print(z)

[[2. 2. 3.]
 [1. 4. 4.]
 [3. 6. 2.]]


In [21]:
#create a 3x3 matrix
import numpy as np
a=np.array([[1,2,3],[3,1,2],[1,2,3]])
print(a)
print(a.shape)

#or

b=np.arange(1,10).reshape(3,3)
print(b)
print(b.shape)
print(b.max())
print(b.max(axis=1))#max element in each row,axis=1 -row,axis=0-column in numpy
print(b.max(axis=0))#maximum element in each column
print(b.min())
print(b.min(axis=1))
print(b.min(axis=0))
print(b.sum())
print(b.sum(axis=1))
print(b.sum(axis=0))
np.sqrt(b)
np.sin(b)
np.cos(b)
np.tan(b)

[[1 2 3]
 [3 1 2]
 [1 2 3]]
(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
9
[3 6 9]
[7 8 9]
1
[1 4 7]
[1 2 3]
45
[ 6 15 24]
[12 15 18]


array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619],
       [ 0.87144798, -6.79971146, -0.45231566]])

In [9]:
#flatten-to change matrix to one dimension
b.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
#sort
#create a 3x3 matrix

a=np.array([[3,4,1],[4,6,7],[3,6,8]])
print(a)
print(a.sum())
print(a.shape)
b=np.sort(a,axis=0)#sort based on column
c=np.sort(a,axis=1)#sort based on row
print(c)
d=np.argsort(a,axis=1)#based on index
print(d)

[[3 4 1]
 [4 6 7]
 [3 6 8]]
42
(3, 3)
[[1 3 4]
 [4 6 7]
 [3 6 8]]
[[2 0 1]
 [0 1 2]
 [0 1 2]]
